# DO NOT USE IN PRODUCTION!

FROM node:6.3
MAINTAINER Nir Galon <nirgn975@gmail.com>

WORKDIR /usr/src/app

RUN npm set progress=false \
&& npm install -g angular-cli typings

COPY package.json typings.json /usr/src/app/
RUN npm install \
&& npm run postinstall

CMD ["npm", "start"]
