<?php

/**
 * @file
 * open_pension_files.module
 */

use Psr\Log\LogLevel;
use \Drupal\open_pension_services\OpenPensionServicesAddresses;
use \Drupal\open_pension_services\OpenPensionServicesHealthStatus;

/**
 * Get the link to the file.
 *
 * @param \Drupal\media\Entity\Media $file
 *  The file object.
 * @param bool $return_url
 *  Determine if we need to return the URl it self.
 * @param null $title
 *  The string of the title.
 *
 * @return string
 *  The HTML string.
 *
 * @deprecated
 */
function open_pension_get_download_link(\Drupal\media\Entity\Media $file, $return_url=FALSE, $title=NULL): string {
  /** @var OpenPensionServicesAddresses $services_addresses */
  $services_addresses = \Drupal::getContainer()->get('open_pension_services.services_addresses');

  if (!$title) {
    $title = t('Download the file');
  }

  $url = Drupal\Core\Url::fromRoute('open_pension_files.get_single_file', ['media' => $file->id()]);

  if ($return_url) {
    return $url->toString();
  }

  return \Drupal\Core\Link::fromTextAndUrl($title, $url)->toString();
}
