# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('label_he', models.CharField(max_length=200, null=True)),
                ('label_en', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundManagingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('fair_value', models.DecimalField(decimal_places=2,
                                                   default=None,
                                                   max_digits=16)),
                ('fund', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='pension.FundManagingBody')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('label_he', models.CharField(max_length=200, null=True)),
                ('label_en', models.CharField(max_length=200, null=True)),
                ('instrument_type', models.IntegerField(
                    choices=[(1, 'Negotiable Security'),
                             (2, 'Non-Negotiable Security')])),
                ('instrument_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('label_he', models.CharField(max_length=200, null=True)),
                ('label_en', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('label_he', models.CharField(max_length=200, null=True)),
                ('label_en', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=None)),
                ('quarter', models.IntegerField(choices=[(1, 'First Quarter'),
                                                         (2, 'Second Quarter'),
                                                         (3, 'Third Quarter'),
                                                         (4, 'Fourth Quarter')]
                                                )),
            ],
        ),
        migrations.AddField(
            model_name='instrument',
            name='issuer',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='pension.Issuer'),
        ),
        migrations.AddField(
            model_name='holding',
            name='instrument',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='pension.Instrument'),
        ),
        migrations.AddField(
            model_name='holding',
            name='quarter',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='pension.Quarter'),
        ),
        migrations.AddField(
            model_name='fundmanagingbody',
            name='end',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quarter_end',
                to='pension.Quarter'),
        ),
        migrations.AddField(
            model_name='fundmanagingbody',
            name='fund',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='pension.Fund'),
        ),
        migrations.AddField(
            model_name='fundmanagingbody',
            name='managing_body',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='pension.ManagingBody'),
        ),
        migrations.AddField(
            model_name='fundmanagingbody',
            name='start',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quarter_start',
                to='pension.Quarter'),
        ),
    ]
