# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='fund_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fund Id'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='fund_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fund Name'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='issuer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Issuer Name'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='negotiable',
            field=models.NullBooleanField(verbose_name='Negotiable'),
        ),
    ]
