# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterfields',
            name='fields_to_show_en',
            field=models.CharField(choices=[('managing_body', 'Managing Body'), ('fund', 'Fund'), ('fund_name', 'Fund Name'), ('instrument_type', 'Instrument Type'), ('instrument_sub_type', 'Instrument Sub Type'), ('instrument_id', 'Instrument ID'), ('orig_instrument_id', 'Orig Instrument Id'), ('instrument_name', 'Instrument Name'), ('issuer', 'Issuer'), ('activity_industry', 'Activity Industry'), ('currency', 'Currency'), ('fair_value', 'Fair Value'), ('market_cap', 'Market Cap'), ('rate_of_fund', 'Rate Of Fund'), ('rating_agency', 'Rating Agency'), ('reference_index', 'Reference Index'), ('intrest_rate', 'Intrest Rate'), ('date_of_purchase', 'Date Of Purchase'), ('average_of_duration', 'Average Of Duration'), ('date_of_revaluation', 'Date Of Revaluation'), ('rate', 'Rate'), ('yield_to_maturity', 'Yield To Maturity'), ('rating', 'Rating'), ('par_value', 'Par Value'), ('underlying_asset', 'Underlying Asset'), ('type_of_asset', 'Type Of Asset'), ('rate_of_ipo', 'Rate Of Ipo'), ('liquidity', 'Liquidity'), ('asset_type', 'Asset Type'), ('row_cleansing_time', 'Row Cleansing Time'), ('issuer_number', 'Issuer Number'), ('owner_option', 'Owner Option'), ('original_issuer_number', 'Original Issuer Number'), ('isin', 'Isin'), ('instrument_symbol', 'Instrument Symbol'), ('movil', 'Movil'), ('sector', 'Sector'), ('dual_trade', 'Dual Trade'), ('cleansing_action', 'Cleansing Action')], max_length=255, null=True, verbose_name='Fields To Show'),
        ),
        migrations.AddField(
            model_name='filterfields',
            name='fields_to_show_he',
            field=models.CharField(choices=[('managing_body', 'Managing Body'), ('fund', 'Fund'), ('fund_name', 'Fund Name'), ('instrument_type', 'Instrument Type'), ('instrument_sub_type', 'Instrument Sub Type'), ('instrument_id', 'Instrument ID'), ('orig_instrument_id', 'Orig Instrument Id'), ('instrument_name', 'Instrument Name'), ('issuer', 'Issuer'), ('activity_industry', 'Activity Industry'), ('currency', 'Currency'), ('fair_value', 'Fair Value'), ('market_cap', 'Market Cap'), ('rate_of_fund', 'Rate Of Fund'), ('rating_agency', 'Rating Agency'), ('reference_index', 'Reference Index'), ('intrest_rate', 'Intrest Rate'), ('date_of_purchase', 'Date Of Purchase'), ('average_of_duration', 'Average Of Duration'), ('date_of_revaluation', 'Date Of Revaluation'), ('rate', 'Rate'), ('yield_to_maturity', 'Yield To Maturity'), ('rating', 'Rating'), ('par_value', 'Par Value'), ('underlying_asset', 'Underlying Asset'), ('type_of_asset', 'Type Of Asset'), ('rate_of_ipo', 'Rate Of Ipo'), ('liquidity', 'Liquidity'), ('asset_type', 'Asset Type'), ('row_cleansing_time', 'Row Cleansing Time'), ('issuer_number', 'Issuer Number'), ('owner_option', 'Owner Option'), ('original_issuer_number', 'Original Issuer Number'), ('isin', 'Isin'), ('instrument_symbol', 'Instrument Symbol'), ('movil', 'Movil'), ('sector', 'Sector'), ('dual_trade', 'Dual Trade'), ('cleansing_action', 'Cleansing Action')], max_length=255, null=True, verbose_name='Fields To Show'),
        ),
        migrations.AlterField(
            model_name='filterfields',
            name='fields_to_show',
            field=models.CharField(choices=[('managing_body', 'Managing Body'), ('fund', 'Fund'), ('fund_name', 'Fund Name'), ('instrument_type', 'Instrument Type'), ('instrument_sub_type', 'Instrument Sub Type'), ('instrument_id', 'Instrument ID'), ('orig_instrument_id', 'Orig Instrument Id'), ('instrument_name', 'Instrument Name'), ('issuer', 'Issuer'), ('activity_industry', 'Activity Industry'), ('currency', 'Currency'), ('fair_value', 'Fair Value'), ('market_cap', 'Market Cap'), ('rate_of_fund', 'Rate Of Fund'), ('rating_agency', 'Rating Agency'), ('reference_index', 'Reference Index'), ('intrest_rate', 'Intrest Rate'), ('date_of_purchase', 'Date Of Purchase'), ('average_of_duration', 'Average Of Duration'), ('date_of_revaluation', 'Date Of Revaluation'), ('rate', 'Rate'), ('yield_to_maturity', 'Yield To Maturity'), ('rating', 'Rating'), ('par_value', 'Par Value'), ('underlying_asset', 'Underlying Asset'), ('type_of_asset', 'Type Of Asset'), ('rate_of_ipo', 'Rate Of Ipo'), ('liquidity', 'Liquidity'), ('asset_type', 'Asset Type'), ('row_cleansing_time', 'Row Cleansing Time'), ('issuer_number', 'Issuer Number'), ('owner_option', 'Owner Option'), ('original_issuer_number', 'Original Issuer Number'), ('isin', 'Isin'), ('instrument_symbol', 'Instrument Symbol'), ('movil', 'Movil'), ('sector', 'Sector'), ('dual_trade', 'Dual Trade'), ('cleansing_action', 'Cleansing Action')], max_length=255, verbose_name='Fields To Show'),
        ),
    ]
