# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentHome',
            fields=[
                ('Investment_home_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('InvestmentFirm_Size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
    ]
