# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
