# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0002_quarter_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='instrument_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.IntegerField(choices=[(1, '1'), (2, '2')]),
        ),
    ]
