# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-09 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0002_investmenthome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmenthome',
            old_name='InvestmentFirm_Size',
            new_name='investment_firm_Size',
        ),
        migrations.RenameField(
            model_name='investmenthome',
            old_name='Investment_home_id',
            new_name='investment_home_id',
        ),
    ]
