# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0002_auto_20180116_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_sub_type',
            field=models.CharField(choices=[('GDC', 'Government Debt Certificates'), ('CDC', 'Commercial Debt Certificates'), ('CB', 'Corporate Bonds'), ('STOCK', 'Stock'), ('IF', 'Investment Funds'), ('ETF', 'ETF'), ('MF', 'Mutual Funds'), ('WARRANTS', 'Warrants'), ('OPTIONS', 'Options'), ('FC', 'Future Contracts'), ('SP', 'Structured Products')], max_length=255, verbose_name='Instrument Sub Type'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MS', 'Marketable Securities'), ('NMS', 'Non-Marketable Securities'), ('DE', 'Deposits'), ('LOANS', 'Loans'), ('DOTM', 'Deposits Over Three Months'), ('LR', 'Land Rights'), ('OI', 'Other Investments'), ('IC', 'Investee Companies'), ('ICB', 'Investment Commitments Balance'), ('CBAC', 'Corporate Bonds Adjusted Cost'), ('BCAC', 'Borrowers Credit Adjusted Cost')], max_length=255, verbose_name='Instrument Type'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='rating',
            field=models.CharField(blank=True, choices=[('AAA+', 'AAA+'), ('AAA', 'AAA'), ('AAA-', 'AAA-'), ('AA+', 'AA+'), ('AA', 'AA'), ('AA-', 'AA-'), ('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('BBB+', 'BBB+'), ('BBB', 'BBB'), ('BBB-', 'BBB-'), ('BB+', 'BB+'), ('BB', 'BB'), ('BB-', 'BB-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('CCC+', 'CCC+'), ('CCC', 'CCC'), ('CCC-', 'CCC-'), ('CC+', 'CC+'), ('CC', 'CC'), ('CC-', 'CC-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('DDD+', 'DDD+'), ('DDD', 'DDD'), ('DDD-', 'DDD-'), ('DD+', 'DD+'), ('DD', 'DD'), ('DD-', 'DD-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('S&P', 'S&P'), ('לא מדורג', 'Not Rated'), ('מעלות', 'From Cost'), ('פנימי', 'Internal'), ('לא דווח', 'No report')], max_length=255, verbose_name='Rating'),
        ),
    ]
