# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0003_auto_20180117_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='activity_industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Activity Industry'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='date_of_purchase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Date Of Purchase'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='date_of_revaluation',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Revaluation'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='expiry_date_of_liabilities',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date Of Liabilities'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='informer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Informer'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='trading_floor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Trading Floor'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type_of_asset',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type Of Asset'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='underlying_asset',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Underlying Asset'),
        ),
    ]
