# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0003_auto_20160909_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmenthome',
            old_name='investment_firm_Size',
            new_name='investment_firm_size',
        ),
    ]
