# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0003_auto_20160507_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.IntegerField(choices=[(1, 'INSTRUMENT TYPE'), (2, '2')]),
        ),
    ]
