# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0004_auto_20160507_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='fair_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
