# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension', '0007_auto_20160511_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(max_length=200),
        ),
    ]
