from django.test import TestCase

class TestPensionApi(TestCase):

    def test_api_root_view(self):
        ''' Test that the root view generated by REST framework works '''
        response = self.client.get('/api/')
        self.assertEqual(response.status_code, 200)
        response = self.client.get('/api')
        self.assertEqual(response.status_code, 301) # 301 - redirecting to /api/
