version: "3.9"

services:
  front:
    env_file:
      - ./front/.env.docker
    ports:
      - "80:3000"

  backoffice:
    environment:
      REACT_APP_API: http://localhost:2001
    ports:
      - '2000:3000'

  backoffice_backend:
    environment:
      PORT: 4000
      dbURL: mongodb://backoffice_backend_db/open_pesion_dashboard
      storageAddress: http://storage:3000
      tempStorageFiles: /app/files
      saltRounds: 10
      tokenTimeToLive: 86400
      kafkaHost: kafka:9092
      listenedTopic: FileStored,fileStoredByService,processingStarted,processedWithErrors,processed
      kafkaOn: 1
    ports:
      - '2001:4000'

  application:
    env_file:
      - ./application/.docker.env
    ports:
      - '3000:3000'
    volumes:
      - ./application:/home/app

  application_db:
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: application
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3308:3306'

  processor:
    env_file:
      - ./processor/.env.docker
    volumes:
      - ./processor/src/app:/app/app
    ports:
      - "1000:80"

  processor_db:
    ports:
      - '27017:27017'

  storage:
    ports:
      - "7000:3000"
    env_file:
      - ./storage/.docker.env

  storage_db:
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: storage
      MYSQL_ROOT_PASSWORD: root

  monthly:
    volumes:
      - ./monthly:/home/app
    ports:
      - "8000:4000"
      - "8555:5555"
    env_file:
      - ./monthly/.docker.env

  monthly_db:
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: monthly
      MYSQL_ROOT_PASSWORD: root

  fetcher:
    volumes:
      - ./fetcher:/home/app
    ports:
      - "5000:80"

  kafka:
    ports:
      - "9092:9092"

  zookeeper:
    ports:
      - "2181:2181"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
