version: "3.9"

services:

  # Databases.

  monthly_db:
    env_file:
      - ./monthly/envs/.local.docker.db.env

  storage_db:
    env_file:
      - ./storage/envs/.local.docker.db.env

  # Services.
  backoffice:
    ports:
      - "1000:80"
    env_file:
      - ./backoffice/envs/.staging.docker.env

  backoffice_backend:
    ports:
      - "2000:80"
    env_file:
      - ./backoffice_backend/envs/.staging.docker.env

  front:
    env_file:
      - ./front/envs/.staging.docker.env
    ports:
      - "80:80"

  gateway:
    ports: []

  monthly:
    env_file:
      - ./monthly/envs/.staging.docker.env

  storage:
    env_file:
      - ./storage/envs/.staging.docker.env
