version: "3.9"

services:
  front:
    env_file:
      - ./front/.env.docker
    ports:
      - "80:3000"

  backoffice:
    environment:
      REACT_APP_API: http://localhost:2001
    ports:
      - '2000:3000'

  backoffice_backend:
    env_file:
      - ./backoffice_backend/.docker.env
    ports:
      - '2001:4000'

  application:
    env_file:
      - ./application/.docker.env
    ports:
      - '3000:3000'
    volumes:
      - ./application:/home/app

  application_db:
    env_file:
      - ./application/.docker.db.env
    ports:
      - '3308:3306'

  processor:
    env_file:
      - ./processor/.env.docker
    volumes:
      - ./processor/src/app:/app/app
    ports:
      - "1000:80"

  processor_db:
    ports:
      - '27017:27017'

  storage:
    ports:
      - "7000:3000"
    env_file:
      - ./storage/.docker.env

  storage_db:
    env_file:
      - ./storage/.docker.db.env

  monthly:
    volumes:
      - ./monthly:/home/app
    ports:
      - "8000:4000"
      - "8555:5555"
    env_file:
      - ./monthly/.docker.env

  monthly_db:
    env_file:
      - ./monthly/.docker.db.env
    environment:

  fetcher:
    volumes:
      - ./fetcher:/home/app
    ports:
      - "5000:80"

  kafka:
    ports:
      - "9092:9092"

  zookeeper:
    ports:
      - "2181:2181"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
