version: "3.9"

services:

  # Databases.
  #  application_db:
  #    env_file:
  #      - ./application/envs/.local.docker.db.env
  #    ports:
  #      - '3308:3306'

  backoffice_backend_db:
    ports:
      - '27017:27017'

  monthly_db:
    env_file:
      - ./monthly/envs/.local.docker.db.env

  storage_db:
    env_file:
      - ./storage/envs/.local.docker.db.env

  # Services.

  backoffice:
    ports:
      - "1000:80"
    env_file:
      - ./backoffice/envs/.local.docker.env

  backoffice_backend:
    ports:
      - "2000:80"
    env_file:
      - ./backoffice_backend/envs/.local.docker.env

  front:
    ports:
      - "3000:80"
    env_file:
      - ./front/envs/.local.docker.env

  monthly:
    ports:
      - "4000:80"
      - "8555:5555"
    env_file:
      - ./monthly/envs/.local.docker.env

  storage:
    ports:
      - "7000:80"
    env_file:
      - ./storage/envs/.local.docker.env
