sheets_order = [
    'סכום נכסי הקרן',
    'מזומנים',
    'תעודות התחייבות ממשלתיות',
    'תעודות חוב מסחריות',
    'אג"ח קונצרני',
    'מניות',
    'תעודות סל',
    'קרנות נאמנות',
    'כתבי אופציה',
    'אופציות',
    'חוזים עתידיים',
    'מוצרים מובנים',
    'לא סחיר - תעודות התחייבות ממשלתי',
    'לא סחיר - תעודות חוב מסחריות',
    'לא סחיר - אג"ח קונצרני',
    'לא סחיר - מניות',
    'לא סחיר - קרנות השקעה',
    'לא סחיר - כתבי אופציה',
    'לא סחיר - אופציות',
    'לא סחיר - חוזים עתידיים',
    'לא סחיר - מוצרים מובנים',
    'הלוואות',
    'פקדונות מעל 3 חודשים',
    'זכויות מקרקעין',
    'השקעה בחברות מוחזקות',
    'השקעות אחרות',
    'יתרת התחייבות להשקעה',
    'עלות מתואמת אג"ח קונצרני סחיר',
    'עלות מתואמת אג"ח קונצרני ל.סחיר',
    'עלות מתואמת מסגרות אשראי ללווים'
]

mapping = {
    'אג"ח קונצרני': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Information provider',
        5: 'Issuer number',
        6: 'Industry',
        7: 'Rating',
        8: 'Rating agencies',
        9: 'Purchase date',
        10: 'Duration',
        11: 'Currency',
        12: 'Rate',
        13: 'Yield to maturity',
        14: 'Nominal value',
        15: 'Price',
        16: 'coupon',
        17: 'Fair value',
        18: 'Rate of register',
        19: 'Rate of instrument type',
        20: 'Rate of fund holding'
    },
    'לא סחיר - אג"ח קונצרני': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Information provider',
        4: 'Issuer number',
        5: 'Industry',
        6: 'Rating',
        7: 'Rating agencies',
        8: 'Purchase date',
        9: 'Duration',
        10: 'Currency',
        11: 'Rate',
        12: 'Yield to maturity',
        13: 'Nominal value',
        14: 'Price',
        15: 'Fair value',
        16: 'Rate of register',
        17: 'Rate of instrument type',
        18: 'Rate of fund holding'
    },
    'אופציות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Industry',
        5: 'Currency',
        6: 'Nominal value',
        7: 'Price',
        8: 'Fair value',
        9: 'Rate of register',
        10: 'Rate of instrument type',
        11: 'Rate of fund holding'
    },
    'לא סחיר - אופציות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Industry',
        4: 'Currency',
        5: 'Purchase date',
        6: 'Nominal value',
        7: 'Price',
        8: 'Fair value',
        9: 'Rate of register',
        10: 'Rate of instrument type',
        11: 'Rate of fund holding'
    },
    'הלוואות': {
        1: 'Instrument name',
        2: 'Consortium',
        3: 'Instrument number',
        4: 'Issuer number',
        5: 'Rating',
        6: 'Purchase date',
        7: 'Rating agencies',
        8: 'Duration',
        9: 'Currency',
        10: 'Rate',
        11: 'Yield to maturity',
        12: 'Nominal value',
        13: 'Price',
        14: 'Fair value',
        15: 'Rate of instrument type',
        16: 'Rate of fund holding'
    },
    'השקעה בחברות מוחזקות': {
        1: 'Instrument name',
        2: 'Issuer number',
        3: 'Rating',
        4: 'Rating agencies',
        5: 'Rate',
        6: 'Currency',
        7: 'Yield to maturity',
        8: 'Fair value',
        9: 'Rate of instrument type',
        10: 'Rate of fund holding'
    },
    'השקעות אחרות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Rating',
        4: 'Rating agencies',
        5: 'Rate',
        6: 'Currency',
        7: 'Yield to maturity',
        8: 'Fair value',
        9: 'Rate of instrument type',
        10: 'Rate of fund holding'
    },
    'זכויות מקרקעין': {
        1: 'Instrument name',
        2: 'Date of valuation',
        3: 'Real estate type',
        4: 'Holding period return/yield',
        5: 'Currency',
        6: 'Fair value',
        7: 'Rate of instrument type',
        8: 'Rate of fund holding',
        9: 'Real estate address'
    },
    'חוזים עתידיים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Industry',
        5: 'Currency',
        6: 'Nominal value',
        7: 'Price',
        8: 'Fair value',
        9: 'Rate of instrument type',
        10: 'Rate of fund holding'
    },
    'לא סחיר - חוזים עתידיים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Industry',
        4: 'Currency',
        5: 'Purchase date',
        6: 'Nominal value',
        7: 'Price',
        8: 'Fair value',
        9: 'Rate of instrument type',
        10: 'Rate of fund holding'
    },
    'יתרת התחייבות להשקעה': {
        1: 'Instrument name',
        2: 'total commitment',
        3: 'Date of investment commitments'
    },
    'כתבי אופציה': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Industry',
        5: 'Currency',
        6: 'Nominal value',
        7: 'Price',
        8: 'Fair value',
        9: 'Rate of register',
        10: 'Rate of instrument type',
        11: 'Rate of fund holding'
    },
    'לא סחיר - כתבי אופציה': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Industry',
        4: 'Currency',
        5: 'Purchase date',
        6: 'Nominal value',
        7: 'Price',
        8: 'Fair value',
        9: 'Rate of register',
        10: 'Rate of instrument type',
        11: 'Rate of fund holding'
    },
    'מוצרים מובנים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Underlying asset',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Purchase date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Yield to maturity',
        11: 'Nominal value',
        12: 'Price',
        13: 'Fair value',
        14: 'Rate of register',
        15: 'Rate of instrument type',
        16: 'Rate of fund holding'
    },
    'לא סחיר - מוצרים מובנים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Underlying asset',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Purchase date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Yield to maturity',
        11: 'Nominal value',
        12: 'Price',
        13: 'Fair value',
        14: 'Rate of register',
        15: 'Rate of instrument type',
        16: 'Rate of fund holding'
    },
    'מניות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Information provider',
        5: 'Issuer number',
        6: 'Industry',
        7: 'Currency',
        8: 'Nominal value',
        9: 'Price',
        10: 'dividend',
        11: 'Fair value',
        12: 'Rate of register',
        13: 'Rate of instrument type',
        14: 'Rate of fund holding'
    },
    'לא סחיר - מניות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Information provider',
        4: 'Issuer number',
        5: 'Industry',
        6: 'Currency',
        7: 'Nominal value',
        8: 'Price',
        9: 'Fair value',
        10: 'Rate of register',
        11: 'Rate of instrument type',
        12: 'Rate of fund holding'
    },
    'פקדונות מעל 3 חודשים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Issuer number',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Duration',
        7: 'Currency',
        8: 'Rate',
        9: 'Yield to maturity',
        10: 'Nominal value',
        11: 'Price',
        12: 'Fair value',
        13: 'Rate of instrument type',
        14: 'Rate of fund holding'
    },
    'לא סחיר - קרנות השקעה': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Currency',
        4: 'Purchase date',
        5: 'Nominal value',
        6: 'Price',
        7: 'Fair value',
        8: 'Rate of register',
        9: 'Rate of instrument type',
        10: 'Rate of fund holding'
    },
    'קרנות נאמנות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Issuer number',
        5: 'Industry',
        6: 'Rating',
        7: 'Rating agencies',
        8: 'Currency',
        9: 'Nominal value',
        10: 'Price',
        11: 'Fair value',
        12: 'Rate of register',
        13: 'Rate of instrument type',
        14: 'Rate of fund holding'
    },
    'תעודות התחייבות ממשלתיות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Purchase date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Yield to maturity',
        11: 'Nominal value',
        12: 'Price',
        13: 'coupon',
        14: 'Fair value',
        15: 'Rate of register',
        16: 'Rate of instrument type',
        17: 'Rate of fund holding'
    },
    'לא סחיר - תעודות התחייבות ממשלתי': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Rating',
        4: 'Rating agencies',
        5: 'Purchase date',
        6: 'Duration',
        7: 'Currency',
        8: 'Rate',
        9: 'Yield to maturity',
        10: 'Nominal value',
        11: 'Price',
        12: 'Fair value',
        13: 'Rate of register',
        14: 'Rate of instrument type',
        15: 'Rate of fund holding'
    },
    'תעודות חוב מסחריות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Information provider',
        5: 'Issuer number',
        6: 'Industry',
        7: 'Rating',
        8: 'Rating agencies',
        9: 'Purchase date',
        10: 'Duration',
        11: 'Currency',
        12: 'Rate',
        13: 'Yield to maturity',
        14: 'Nominal value',
        15: 'Price',
        16: 'Fair value',
        17: 'Rate of register',
        18: 'Rate of instrument type',
        19: 'Rate of fund holding'
    },
    'לא סחיר - תעודות חוב מסחריות': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Information provider',
        4: 'Issuer number',
        5: 'Industry',
        6: 'Rating',
        7: 'Rating agencies',
        8: 'Purchase date',
        9: 'Duration',
        10: 'Currency',
        11: 'Rate',
        12: 'Yield to maturity',
        13: 'Nominal value',
        14: 'Price',
        15: 'Fair value',
        16: 'Rate of register',
        17: 'Rate of instrument type',
        18: 'Rate of fund holding'
    },
    'תעודות סל': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Market name',
        4: 'Issuer number',
        5: 'Industry',
        6: 'Currency',
        7: 'Nominal value',
        8: 'Price',
        9: 'coupon',
        10: 'Fair value',
        11: 'Rate of register',
        12: 'Rate of instrument type',
        13: 'Rate of fund holding'
    },
    'עלות מתואמת אג"ח קונצרני ל.סחיר': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Industry',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Purchase date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Effective interest',
        11: 'Nominal value',
        12: 'Fair value',
        13: 'Rate of register',
        14: 'Rate of instrument type',
        15: 'Rate of fund holding'
    },
    'עלות מתואמת אג"ח קונצרני סחיר': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Industry',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Purchase date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Effective interest',
        11: 'Fair value',
        12: 'Fair value',
        13: 'Rate of register',
        14: 'Rate of instrument type',
        15: 'Rate of fund holding'
    },
    'מזומנים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Issuer number',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Currency',
        7: 'Rate',
        8: 'Yield to maturity',
        9: 'Fair value',
        10: 'Rate of instrument type',
        11: 'Rate of fund holding'
    },
    'עלות מתואמת מסגרות אשראי ללווים': {
        1: 'Instrument name',
        2: 'Instrument number',
        3: 'Industry',
        4: 'Rating',
        5: 'Rating agencies',
        6: 'Purchase date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Effective interest',
        11: 'Nominal value',
        12: 'Fair value',
        13: 'Rate of register',
        14: 'Rate of instrument type',
        15: 'Rate of fund holding'
    }
}
