sheets_order = [
    'סכום נכסי הקרן',
    'מזומנים',
    'תעודות התחייבות ממשלתיות',
    'תעודות חוב מסחריות',
    'אג"ח קונצרני',
    'מניות',
    'תעודות סל',
    'קרנות נאמנות',
    'כתבי אופציה',
    'אופציות',
    'חוזים עתידיים',
    'מוצרים מובנים',
    'לא סחיר - תעודות התחייבות ממשלתי',
    'לא סחיר - תעודות חוב מסחריות',
    'לא סחיר - אג"ח קונצרני',
    'לא סחיר - מניות',
    'לא סחיר - קרנות השקעה',
    'לא סחיר - כתבי אופציה',
    'לא סחיר - אופציות',
    'לא סחיר - חוזים עתידיים',
    'לא סחיר - מוצרים מובנים',
    'הלוואות',
    'פקדונות מעל 3 חודשים',
    'זכויות מקרקעין',
    'השקעה בחברות מוחזקות',
    'השקעות אחרות',
    'יתרת התחייבות להשקעה',
    'עלות מתואמת אג"ח קונצרני סחיר',
    'עלות מתואמת אג"ח קונצרני ל.סחיר',
    'עלות מתואמת מסגרות אשראי ללווים'
]

mapping = {
    'אג"ח קונצרני': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Information provider',
        5: 'Issuer Nunber',
        6: 'Industry',
        7: 'Rating',
        8: 'Rating Agencies',
        9: 'Purcahse date',
        10: 'Duration',
        11: 'Currency',
        12: 'Rate',
        13: 'yield to maturity',
        14: 'Nominal Value',
        15: 'Price',
        16: 'coupon',
        17: 'Market Value',
        18: 'Rafe of Register',
        19: 'Rate of Instrument Type',
        20: 'Rafe of Funde Holding'
    },
    'לא סחיר - אג"ח קונצרני': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Information provider',
        4: 'Issuer Nunber',
        5: 'Industry',
        6: 'Rating',
        7: 'Rating Agencies',
        8: 'Purcahse date',
        9: 'Duration',
        10: 'Currency',
        11: 'Rate',
        12: 'yield to maturity',
        13: 'Nominal Value',
        14: 'Price',
        15: 'Fair Value',
        16: 'Rafe of Register',
        17: 'Rate of Instrument Type',
        18: 'Rafe of Funde Holding'},
    'אופציות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Industry',
        5: 'Currency',
        6: 'Nominal Value',
        7: 'Price',
        8: 'Market Value',
        9: 'Rafe of Register',
        10: 'Rate of Instrument Type',
        11: 'Rafe of Funde Holding'
    },
    'לא סחיר - אופציות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Industry',
        4: 'Currency',
        5: 'Purcahse date',
        6: 'Nominal Value',
        7: 'Price',
        8: 'Fair Value',
        9: 'Rafe of Register',
        10: 'Rate of Instrument Type',
        11: 'Rafe of Funde Holding'
    },
    'הלוואות': {
        1: 'Instrument Name',
        2: 'Consortium',
        3: 'Instrument Number',
        4: 'Issuer Nunber',
        5: 'Rating',
        6: 'Purcahse date',
        7: 'Rating Agencies',
        8: 'Duration',
        9: 'Currency',
        10: 'Rate',
        11: 'yield to maturity',
        12: 'Nominal Value',
        13: 'Price',
        14: 'Fair Value',
        15: 'Rate of Instrument Type',
        16: 'Rafe of Funde Holding'
    },
    'השקעה בחברות מוחזקות': {
        1: 'Instrument Name',
        2: 'Issuer Nunber',
        3: 'Rating',
        4: 'Rating Agencies',
        5: 'Rate',
        6: 'Currency',
        7: 'yield to maturity',
        8: 'Fair Value',
        9: 'Rate of Instrument Type',
        10: 'Rafe of Funde Holding'
    },
    'השקעות אחרות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Rating',
        4: 'Rating Agencies',
        5: 'Rate',
        6: 'Currency',
        7: 'yield to maturity',
        8: 'Fair Value',
        9: 'Rate of Instrument Type',
        10: 'Rafe of Funde Holding'
    },
    'זכויות מקרקעין': {
        1: 'Instrument Name',
        2: 'Date of valuation',
        3: 'Real Estate Type',
        4: 'Holding Period Return/Yield',
        5: 'Currency',
        6: 'Fair Value',
        7: 'Rate of Instrument Type',
        8: 'Rafe of Funde Holding',
        9: 'Real Estate address'
    },
    'חוזים עתידיים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Industry',
        5: 'Currency',
        6: 'Nominal Value',
        7: 'Price',
        8: 'Market Value',
        9: 'Rate of Instrument Type',
        10: 'Rafe of Funde Holding'
    },
    'לא סחיר - חוזים עתידיים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Industry',
        4: 'Currency',
        5: 'Purcahse date',
        6: 'Nominal Value',
        7: 'Price',
        8: 'Fair Value',
        9: 'Rate of Instrument Type',
        10: 'Rafe of Funde Holding'
    },
    'יתרת התחייבות להשקעה': {
        1: 'Instrument Name',
        2: 'total commitment',
        3: 'Date of Investment commitments'
    },
    'כתבי אופציה': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Industry',
        5: 'Currency',
        6: 'Nominal Value',
        7: 'Price',
        8: 'Market Value',
        9: 'Rafe of Register',
        10: 'Rate of Instrument Type',
        11: 'Rafe of Funde Holding'},
    'לא סחיר - כתבי אופציה': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Industry',
        4: 'Currency',
        5: 'Purcahse date',
        6: 'Nominal Value',
        7: 'Price',
        8: 'Fair Value',
        9: 'Rafe of Register',
        10: 'Rate of Instrument Type', 11: 'Rafe of Funde Holding'
    },
    'מוצרים מובנים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Underlying asset',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Purcahse date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'yield to maturity',
        11: 'Nominal Value',
        12: 'Price',
        13: 'Market Value',
        14: 'Rafe of Register',
        15: 'Rate of Instrument Type',
        16: 'Rafe of Funde Holding'
    },
    'לא סחיר - מוצרים מובנים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Underlying asset',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Purcahse date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'yield to maturity',
        11: 'Nominal Value',
        12: 'Price',
        13: 'Fair Value',
        14: 'Rafe of Register',
        15: 'Rate of Instrument Type',
        16: 'Rafe of Funde Holding'
    },
    'מניות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Information provider',
        5: 'Issuer Nunber',
        6: 'Industry',
        7: 'Currency',
        8: 'Nominal Value',
        9: 'Price',
        10: 'dividend',
        11: 'Market Value',
        12: 'Rafe of Register',
        13: 'Rate of Instrument Type',
        14: 'Rafe of Funde Holding'
    },
    'לא סחיר - מניות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Information provider',
        4: 'Issuer Nunber',
        5: 'Industry',
        6: 'Currency',
        7: 'Nominal Value',
        8: 'Price',
        9: 'Fair Value',
        10: 'Rafe of Register',
        11: 'Rate of Instrument Type',
        12: 'Rafe of Funde Holding'},
    'פקדונות מעל 3 חודשים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Issuer Nunber',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Duration',
        7: 'Currency',
        8: 'Rate',
        9: 'yield to maturity',
        10: 'Nominal Value',
        11: 'Price',
        12: 'Fair Value',
        13: 'Rate of Instrument Type',
        14: 'Rafe of Funde Holding'
    },
    'לא סחיר - קרנות השקעה': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Currency',
        4: 'Purcahse date',
        5: 'Nominal Value',
        6: 'Price',
        7: 'Fair Value',
        8: 'Rafe of Register',
        9: 'Rate of Instrument Type',
        10: 'Rafe of Funde Holding'
    },
    'קרנות נאמנות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Issuer Nunber',
        5: 'Industry',
        6: 'Rating',
        7: 'Rating Agencies',
        8: 'Currency',
        9: 'Nominal Value',
        10: 'Price',
        11: 'Market Value',
        12: 'Rafe of Register',
        13: 'Rate of Instrument Type',
        14: 'Rafe of Funde Holding'
    },
    'תעודות התחייבות ממשלתיות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Purcahse date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'yield to maturity',
        11: 'Nominal Value',
        12: 'Price',
        13: 'coupon',
        14: 'Market Value',
        15: 'Rafe of Register',
        16: 'Rate of Instrument Type',
        17: 'Rafe of Funde Holding'
    },
    'לא סחיר - תעודות התחייבות ממשלתי': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Rating',
        4: 'Rating Agencies',
        5: 'Purcahse date',
        6: 'Duration',
        7: 'Currency',
        8: 'Rate',
        9: 'yield to maturity',
        10: 'Nominal Value',
        11: 'Price',
        12: 'Fair Value',
        13: 'Rafe of Register',
        14: 'Rate of Instrument Type',
        15: 'Rafe of Funde Holding'
    },
    'תעודות חוב מסחריות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Information provider',
        5: 'Issuer Nunber',
        6: 'Industry',
        7: 'Rating',
        8: 'Rating Agencies',
        9: 'Purcahse date',
        10: 'Duration',
        11: 'Currency',
        12: 'Rate',
        13: 'yield to maturity',
        14: 'Nominal Value',
        15: 'Price',
        16: 'Market Value',
        17: 'Rafe of Register',
        18: 'Rate of Instrument Type',
        19: 'Rafe of Funde Holding'
    },
    'לא סחיר - תעודות חוב מסחריות': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Information provider',
        4: 'Issuer Nunber',
        5: 'Industry',
        6: 'Rating',
        7: 'Rating Agencies',
        8: 'Purcahse date',
        9: 'Duration',
        10: 'Currency',
        11: 'Rate',
        12: 'yield to maturity',
        13: 'Nominal Value',
        14: 'Price',
        15: 'Fair Value',
        16: 'Rafe of Register',
        17: 'Rate of Instrument Type',
        18: 'Rafe of Funde Holding'
    },
    'תעודות סל': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Market name',
        4: 'Issuer Nunber',
        5: 'Industry',
        6: 'Currency',
        7: 'Nominal Value',
        8: 'Price',
        9: 'coupon',
        10: 'Market Value',
        11: 'Rafe of Register',
        12: 'Rate of Instrument Type',
        13: 'Rafe of Funde Holding'
    },
    'עלות מתואמת אג"ח קונצרני ל.סחיר': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Industry',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Purcahse date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Effective intrests',
        11: 'Nominal Value',
        12: 'Fair Value',
        13: 'Rafe of Register',
        14: 'Rate of Instrument Type',
        15: 'Rafe of Funde Holding'
    },
    'עלות מתואמת אג"ח קונצרני סחיר': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Industry',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Purcahse date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Effective intrests',
        11: 'Fair Value',
        12: 'Fair Value',
        13: 'Rafe of Register',
        14: 'Rate of Instrument Type',
        15: 'Rafe of Funde Holding'
    },
    'מזומנים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Issuer Nunber',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Currency',
        7: 'Rate',
        8: 'yield to maturity',
        9: 'Market Value',
        10: 'Rate of Instrument Type',
        11: 'Rafe of Funde Holding'
    },
    'עלות מתואמת מסגרות אשראי ללווים': {
        1: 'Instrument Name',
        2: 'Instrument Number',
        3: 'Industry',
        4: 'Rating',
        5: 'Rating Agencies',
        6: 'Purcahse date',
        7: 'Duration',
        8: 'Currency',
        9: 'Rate',
        10: 'Effective intrests',
        11: 'Nominal Value',
        12: 'Fair Value',
        13: 'Rafe of Register',
        14: 'Rate of Instrument Type',
        15: 'Rafe of Funde Holding'
    }
}
