
PENSION_HEB_TO_ENG = {
    'אג"ח קונצרני': 'Corporate Bond',
    'אופציות':'Option',
    'הלוואות':'Loans',
    'השקעה בחברות מוחזקות':'Investee Companies',
    'השקעות אחרות':'Other Investments',
    'זכויות מקרקעין':'Real Estate',
    'חוזים עתידיים':'Future',
    'כתבי אופציה':'Warrant',
    'מוצרים מובנים':'Structured',
    'מזומנים':'Cash',
    'מניות':'Stock',
    'פקדונות מעל 3 חודשים':'Deposits',
    'קרנות השקעה':'Private Equity',
    'תעודות השתתפות בקרנות נאמנות':'Mutual Fund',
    'תעודות התחייבות ממשלתיות':'Government Bond',
    'תעודות חוב מסחריות':'Commercial Debt',
    'תעודות סל':'ETF',
    'מספר קרן':'Fund Number',
    'שם קרן':'Fund Nane',
    'סוג קרן':'Fund Type',
    'גוף מוסדי':'Institutional body',
    'סחירות':'Tradable',
    'ארץ':'Country',
    'סוג מטבע':'Currency',
    'שם מנפיק':'Issuer Mane',
    'מספר מנפיק':'Issuer Nunber',
    'יעודיות':'Designated Bond',
    'סוג קרן':'Investmnet Fund Type',
    'נדלן':'Real Estate Type',
    'סוג הלוואה':'Loan Type',
    'סוג נגזר':'Derivative Type',
    'סוג מוצר':'Structured Type',
    'חברות':'Commercial Country',
    'ממשלה':'Government Bond',
    'שייך למדד':'Index',
    'הצמדה':'Protected',
    'ענף פעילות':'Industry',
    'דירוג':'Rating',
    'נכס בסיס':'Underlying',
    'אתר':'Web',
    'כתובת הנכס':'Real Estate address',
    'מח"מ':'Duration',
    'מספר מנפיק':'Issuer Number',
    'מספר ני"ע':'Instrument Number',
    'ערך נקוב':'Nominal Value',
    'קונסורציום כן/לא':'Consortium',
    'שיעור ריבית':'Rate',
    'שם המדרג':'Rating Agencies',
    'שם המנפיק/שם נייר ערך':'Instrument Name',
    'שעור מנכסי אפיק ההשקעה':'Rate of Instrument Type',
    'שעור מסך נכסי השקעה':'Rafe of Funde Holding',
    'שעור מערך נקוב מונפק':'Rafe of Register',
    'שער':'Price',
    'תשואה לפידיון':'yield'
}


def translate_from_hebrew(word):
    if word in PENSION_HEB_TO_ENG:
        return PENSION_HEB_TO_ENG[word]

