export default {
    1: 'Instrument name',
    2: 'Instrument number',
    3: 'Market name',
    4: 'Information provider',
    5: 'Issuer number',
    6: 'Industry',
    7: 'Rating',
    8: 'Rating agencies',
    9: 'Purchase date',
    10: 'Duration',
    11: 'Currency',
    12: 'Rate',
    13: 'Yield to maturity',
    14: 'Nominal value',
    15: 'Price',
    16: 'coupon',
    17: 'Fair value',
    18: 'Rate of register',
    19: 'Rate of instrument type',
    20: 'Rate of fund holding'
};
