YEARS = (
    ('2018', '2018'),
    ('2017', '2017'),
    ('2016', '2016'),
    ('2015', '2015'),
    ('2014', '2014'),
    ('2013', '2013'),
    ('2012', '2012'),
)

MONTHS = (
    ('1', '01'),
    ('2', '02'),
    ('3', '03'),
    ('4', '04'),
)

MANAGING_BODIES = (
    ('AS', 'Altshuler Shaham'),
    ('YL', 'Yelin Lapidot'),
    ('CLL', 'Clal Insurance'),
    ('AMT', 'Amitim'),
    ('MTD', 'Meitav Dash'),
    ('FNX', 'Phoenix'),
    ('HRL', 'Harel'),
    ('MNR', 'Menora Mivtachim'),
    ('MGD', 'Migdal'),
    ('PSG', 'Psagot'),
    ('XNS', 'Excellence'),
)

INSTRUMENT_SUB_TYPES = (
    ('GDC', 'Government Debt Certificates'),
    ('CDC', 'Commercial Debt Certificates'),
    ('CB', 'Corporate Bonds'),
    ('STOCK', 'Stock'),
    ('IF', 'Investment Funds'),
    ('ETF', 'ETF'),
    ('MF', 'Mutual Funds'),
    ('WARRANTS', 'Warrants'),
    ('OPTIONS', 'Options'),
    ('FC', 'Future Contracts'),
    ('SP', 'Structured Products'),
)

INSTRUMENT_TYPES = (
    ('CASH', 'Cash'),
    ('MS', 'Marketable Securities'),
    ('NMS', 'Non-Marketable Securities'),
    ('DE', 'Deposits'),
    ('LOANS', 'Loans'),
    ('DOTM', 'Deposits Over Three Months'),
    ('LR', 'Land Rights'),
    ('OI', 'Other Investments'),
    ('IC', 'Investee Companies'),
    ('ICB', 'Investment Commitments Balance'),
    ('CBAC', 'Corporate Bonds Adjusted Cost'),
    ('BCAC', 'Borrowers Credit Adjusted Cost'),
)

INSTRUMENT_FIELDS = (
    ('managing_body', 'Managing Body'),
    ('fund', 'Fund'),
    ('fund_name', 'Fund Name'),
    ('instrument_type', 'Instrument Type'),
    ('instrument_sub_type', 'Instrument Sub Type'),
    ('instrument_id', 'Instrument ID'),
    ('orig_instrument_id', 'Orig Instrument Id'),
    ('instrument_name', 'Instrument Name'),
    ('issuer', 'Issuer'),
    ('activity_industry', 'Activity Industry'),
    ('currency', 'Currency'),
    ('fair_value', 'Fair Value'),
    ('market_cap', 'Market Cap'),
    ('rate_of_fund', 'Rate Of Fund'),
    ('rating_agency', 'Rating Agency'),
    ('reference_index', 'Reference Index'),
    ('intrest_rate', 'Intrest Rate'),
    ('date_of_purchase', 'Date Of Purchase'),
    ('average_of_duration', 'Average Of Duration'),
    ('date_of_revaluation', 'Date Of Revaluation'),
    ('rate', 'Rate'),
    ('yield_to_maturity', 'Yield To Maturity'),
    ('rating', 'Rating'),
    ('par_value', 'Par Value'),
    ('underlying_asset', 'Underlying Asset'),
    ('type_of_asset', 'Type Of Asset'),
    ('rate_of_ipo', 'Rate Of Ipo'),
    ('liquidity', 'Liquidity'),
    ('asset_type', 'Asset Type'),
    ('row_cleansing_time', 'Row Cleansing Time'),
    ('issuer_number', 'Issuer Number'),
    ('owner_option', 'Owner Option'),
    ('original_issuer_number', 'Original Issuer Number'),
    ('isin', 'Isin'),
    ('instrument_symbol', 'Instrument Symbol'),
    ('movil', 'Movil'),
    ('sector', 'Sector'),
    ('dual_trade', 'Dual Trade'),
    ('cleansing_action', 'Cleansing Action'),
)

RATING = (
    ('AAA+', 'AAA+'),
    ('AAA', 'AAA'),
    ('AAA-', 'AAA-'),
    ('AA+', 'AA+'),
    ('AA', 'AA'),
    ('AA-', 'AA-'),
    ('A+', 'A+'),
    ('A', 'A'),
    ('A-', 'A-'),
    ('BBB+', 'BBB+'),
    ('BBB', 'BBB'),
    ('BBB-', 'BBB-'),
    ('BB+', 'BB+'),
    ('BB', 'BB'),
    ('BB-', 'BB-'),
    ('B+', 'B+'),
    ('B', 'B'),
    ('B-', 'B-'),
    ('CCC+', 'CCC+'),
    ('CCC', 'CCC'),
    ('CCC-', 'CCC-'),
    ('CC+', 'CC+'),
    ('CC', 'CC'),
    ('CC-', 'CC-'),
    ('C+', 'C+'),
    ('C', 'C'),
    ('C-', 'C-'),
    ('DDD+', 'DDD+'),
    ('DDD', 'DDD'),
    ('DDD-', 'DDD-'),
    ('DD+', 'DD+'),
    ('DD', 'DD'),
    ('DD-', 'DD-'),
    ('D+', 'D+'),
    ('D', 'D'),
    ('D-', 'D-'),
    ('S&P', 'S&P'),
    ('לא מדורג', 'Not Rated'),
    ('מעלות', 'From Cost'),
    ('פנימי', 'Internal'),
    ('לא דווח', 'No report'),
)
