# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-16 17:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('title_he', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='body')),
                ('body_he', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('body_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='body')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='author')),
                ('author_he', models.CharField(blank=True, max_length=255, null=True, verbose_name='author')),
                ('author_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='author')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(null=True, verbose_name='publish')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='tag')),
                ('name_he', models.CharField(max_length=255, null=True, unique=True, verbose_name='tag')),
                ('name_en', models.CharField(max_length=255, null=True, unique=True, verbose_name='tag')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'verbose_name': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='תגיות', to='blog.Tags'),
        ),
    ]
