# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 15:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Share Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_he',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(null=True, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
