# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180310_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_image_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Share Image'),
        ),
        migrations.AddField(
            model_name='post',
            name='share_image_he',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Share Image'),
        ),
    ]
