-- CreateTable
CREATE TABLE `File` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `storageID` INTEGER NOT NULL,
    `filename` VARCHAR(191) NOT NULL,
    `path` LONGTEXT NOT NULL,
    `created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `status` ENUM('Ready', 'Succeeded', 'Failed') NOT NULL DEFAULT 'Ready',
    `error` LONGTEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Row` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `fileId` INTEGER NOT NULL,
    `created` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `MANAGER_ID` INTEGER NOT NULL,
    `ALPHA_SHNATI` DOUBLE NOT NULL,
    `SHARP_RIBIT_HASRAT_SIKUN` DOUBLE NOT NULL,
    `STIAT_TEKEN_60_HODASHIM` DOUBLE NOT NULL,
    `STIAT_TEKEN_36_HODASHIM` DOUBLE NOT NULL,
    `TSUA_SHNATIT_MEMUZAAT_5_SHANIM` DOUBLE NOT NULL,
    `TSUA_SHNATIT_MEMUZAAT_3_SHANIM` DOUBLE NOT NULL,
    `TSUA_MITZTABERET_60_HODASHIM` DOUBLE NOT NULL,
    `TSUA_MITZTABERET_36_HODASHIM` DOUBLE NOT NULL,
    `TSUA_MEMUZAAT_60_HODASHIM` DOUBLE NOT NULL,
    `TSUA_MEMUZAAT_36_HODASHIM` DOUBLE NOT NULL,
    `TSUA_MITZT_MI_THILAT_SHANA` DOUBLE NOT NULL,
    `YITRAT_NCHASIM_LSOF_TKUFA` DOUBLE NOT NULL,
    `TSUA_NOMINALIT_BRUTO_HODSHIT` DOUBLE NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Row` ADD FOREIGN KEY (`fileId`) REFERENCES `File`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
