name: Unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.9.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ./.github/actions/unit
        env:
          CI: true
        with:
          folder: backoffice
