name: Unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  backoffice:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.9.0 ]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/unit
        env:
          CI: true
        with:
          node-version: ${{ matrix.node-version }}
          folder: backoffice
      - name: run jest
        env:
          CI: true
        run: |
          cd backoffice
          npm run test
  backoffice_backend:
      runs-on: ubuntu-20.04

      strategy:
        matrix:
          node-version: [ 16.9.0 ]

      steps:
        - uses: actions/checkout@v2
        - uses: ./.github/actions/unit
          env:
            CI: true
          with:
            node-version: ${{ matrix.node-version }}
            folder: backoffice_backend
        - name: run jest
          env:
            CI: true
          run: |
            cd backoffice_backend
            npm run jest --ci --watchAll=false
  front:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.9.0 ]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/unit
        env:
          CI: true
        with:
          node-version: ${{ matrix.node-version }}
          folder: front
      - name: run jest
        env:
          CI: true
        run: |
          cd front
          npm run test:ci
  monthly:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.9.0 ]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/unit
        env:
          CI: true
        with:
          node-version: ${{ matrix.node-version }}
          folder: front

      - name: Install dependencies
        run: |
          cd monthly
          npm run prisma:clientGenerate
          npm run prisma:migrate
      - name: run jest
        env:
          CI: true
        run: cd monthly && npm run jest
  storage:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.9.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up the storage service
        run: |
          cd storage
          docker-compose up -d storage storage_db
          # Sleeping for 30 seconds to wait for the server to be ready
          sleep 30

      - name: Fixing permissions
        run: |
          ls -al
          pwd
          sudo chmod 777 storage/testing/src/tests/assets/cat.png
          sudo chmod 777 data/files/storage

      - name: Install dependencies
        run: |
          cd storage/testing
          npm i
          npm run prisma:clientGenerate
          npm run prisma:migrate
      - name: run jest
        env:
          CI: true
          DATABASE_URL: mysql://root:root@localhost:3308/storage?schema=public
        run: |
          cd storage/testing
          npm run test

