name: Services unit testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  backoffice:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [ 16.9.0 ]

    steps:
      - uses: actions/checkout@v2
      - name: Run unit
        uses: actions/run-unit@v1
        env:
          CI: true
        with:
          service: backoffice
          node-version: ${{ matrix.node-version }}
